<template>
  <div>
    <div style="display:flex;justify-content:center;position:relative; height:60px">
      <div class=heading>Select a category to practise</div>
        <router-link style="position:fixed;text-decoration:none;right:0;" to="/settings">
          <font-awesome-icon style="font-size:75;color:rgba(142, 142, 147);" icon="cog"/>
        </router-link>
    </div>
    
    <!-- This is the Select Buttons, the first div the inbuilt lists and the second div is the custom lists, the buttons are autogenerated-->
    <div style="display:flex; align-itmes:center; justify-content:left; flex-wrap:wrap; margin-top: 10px">
      
      <div v-for="(list, index) in lists" v-bind:key="index" style="display:flex; align-items:center;  margin:10px">
        <SelectButton :preset="preset.selected[index]" :index="index" :title="list" v-on:update:value="temp=$event" :image_path="inbuiltImagesLists[index]"/>
      </div>

      <div v-for="(customList, index) in customLists" v-bind:key="index + inbuiltWordlists.length" style="display:flex; align-items:center; margin:10px" >
        <SelectButton :preset="preset.customSelected[index]" :index="index + inbuiltWordlists.length" :title="customList" v-on:update:value="temp=$event" :image_path="inbuiltImagesLists[index + inbuiltWordlists.length]" />
      </div>
    </div>
    
    <div style="width:460px;margin:auto" v-if="!hidden" class="box">
      <router-link style="display:flex;justify-content:center;align-items:center;text-decoration:none" :to="startTo" >
        <p style="text-align:center;font-size:40px;margin-right:16px;color:black">START</p>
        <font-awesome-icon style="font-size:100;color:black" icon="chevron-right"/>
      </router-link>
    </div>
  </div>
</template>

<script>
  import SelectButton from '@/components/SelectButton.vue';
  import InbuiltWordlists from '@/components/InbuiltWordlists.js';
  import InbuiltImagesLists from '@/components/InbuiltImageLists.js';
  import Cookies from '@/components/Cookies.js';
  
  export default {
    data() {
      return {
        //Inbuilt lists
        lists: [],
        words: [],
        selected: [],
        //Custom lists
        customLists: [],
        customWords: [],
        customSelected: [],
        temp: null,
        hidden: true,
        preset: {
          selected: [],
          customSelected: [],
        },
        startTo: "/keyboard",
        inbuiltImagesLists : InbuiltImagesLists,
        inbuiltWordlists : InbuiltWordlists,
        cookies : Cookies,
        cookieNames: [],
        cookieInitialValues: [],
      }
    },
    components: {
      'SelectButton' : SelectButton,
    },
    created() {
      // Initialise settings cookies
      this.cookiesCreated(this.cookies);
      for (var x = 0; x < this.cookieNames[0].length; x++) {
        if (!this.$cookies.isKey(this.cookieNames[0][x])) {
          this.$cookies.set(this.cookieNames[0][x], this.cookieInitialValues[0][x]);
        }
      }
      
      // Import inbuilt lists from cookies
      if (this.$cookies.isKey('select_words.built_in_selected')) {
        this.preset.selected = JSON.parse("[" + this.$cookies.get('select_words.built_in_selected') + "]");
      } else {
        var size = this.inbuiltWordlists.length;
        this.preset.selected = Array.apply(null, Array(size)).map(Boolean.prototype.valueOf,false);
      }
      
      // Importing the custom lists and whether they are selected from cookies
      if (this.$cookies.isKey('custom_word_lists.lists')) {
        this.customLists = this.$cookies.get('custom_word_lists.lists').split(',');
        if (this.$cookies.isKey('select_words.custom_selected')) {
          window.console.log(this.$cookies.get('select_words.custom_selected'))
          this.preset.customSelected = JSON.parse("[" + this.$cookies.get('select_words.custom_selected') + "]");
        } else {
          this.preset.customSelected = Array.apply(null, Array(this.customLists.length)).map(Boolean.prototype.valueOf,false);
        }
      }
      
      if (this.$cookies.isKey('custom_word_lists.words')) {
        var words = this.$cookies.get('custom_word_lists.words').split('|').slice(0,-1);
        for (var i = 0; i < words.length; i++){
          if (words[i].includes(',')) {
            this.customWords.push(words[i].split(','));
          } else {
            this.customWords.push(words[i]);
          }
        }
      }
      
      this.selected = this.preset.selected;
      this.customSelected = this.preset.customSelected;
      this.inbuiltCreated(this.inbuiltWordlists)
      if(this.selected.includes(true) || this.customSelected.includes(true)) {
            this.hidden = false;
          } else {
            this.hidden = true;
          }
    },
    methods: {
      inbuiltCreated(wordlists) {
        for (var i = 0; i < wordlists.length; i++) {
          this.lists.push(Object.keys(wordlists[i])[0]);
          this.words.push(Object.values(wordlists[i])[0]);
        }
      },
      cookiesCreated(cookies) {
        this.cookieNames.push(Object.values(cookies[0])[0]);
        this.cookieInitialValues.push(Object.values(cookies[1])[0]); 
      }
    },
    
    watch: {
      'temp' : function(val){
        if (val.index < this.inbuiltWordlists.length) {
          this.selected[val.index] = val.value;
          this.$cookies.set('select_words.built_in_selected', this.selected);
        } else {
          this.customSelected[val.index - this.inbuiltWordlists.length] = val.value;
          this.$cookies.set('select_words.custom_selected', this.customSelected);
        }
        if(this.selected.includes(true) || this.customSelected.includes(true)) {
          this.hidden = false;
        } else {
          this.hidden = true;
        }
      }
    } 
  }
</script>


<style scoped>
  .heading {
    font-size:40px;
    text-align: center;
    color: rgba(44, 44, 46, 0.5);
  }
  
  .list-heading {
    font-size:22px;
    text-align: left;
  }
</style>
